### ISSUE TITLE
Usage Of removeItem

### ISSUE THREAD

**Issue by buzkanlamaca** [nils-soderman/CtxMenu-Javascript#3]
For some cases i must remove some items from menu and add new ones. As i see in your code, there is a removeItem property. How can i use it? For example what is the usage of removeItem if i want to remove the first item from the menu?

**Comment by nils-soderman** [comment]
Hi @buzkanlamaca,

Nice catch, seems like the `removeItem()` function was never really implemented properly.
I've pushed a new release [v1.0.1](https://github.com/nils-soderman/CtxMenu-Javascript/releases/tag/v1.0.1) that removes this function and instead adds `getItemAtIndex()` & `getItems()`.

So now if you e.g. want to remove the first item you'd do something like: 
```javascript
myContextMenu.getItemAtIndex(0).remove();
```

Alternatively you can also store the item as a variable when you create it, and remove it later.
```javascript
let myItem = myContextMenu.addItem("Hello World", myFunction);
myItem.remove();
```
