### ISSUE TITLE
[question]  multiple context menus

### ISSUE THREAD

**Issue by emicklei** [nils-soderman/CtxMenu-Javascript#4]
Hi,

I am considering using your contextmenu solution.
On my page, I have multiple list widgets in which I can select items.
I want a context menu for each list widget.
Can I use your solution and if so do you a suggestion how to apply it?

thanks.

**Comment by nils-soderman** [comment]
Hi,

Sorry for the super late reply, I hope you've already found a solution for your case.
But yes, it should be possible to use this solution.

Let's say you have something similar to this:
````html
<div id="MyFirstList" class="ListWidget"> ... </div>
<div id="MySecondList" class="ListWidget"> ... </div>
````

Then you can either create unique context menus for each widget, example:
````js
var myFirstContextMenu = CtxMenu("#MyFirstList");
var mySecondContextMenu = CtxMenu("#MySecondList");
// Populate the context menus...
````

Or create a shared context menu for all of those widgets:
````js
var myContextMenu = CtxMenu(".ListWidget");
// Populate the context menu...
````

<br/>
Best Regards,<br/>
Nils Söderman
